splunk:
  opt: /opt
  home: /opt/splunk
  user: splunk
  group: splunk
  svc_port: 8089
  s2s_port: 9997
  http_port: 8000
  hec:
    enable: True
    ssl: False
    port: 8088
    token: abcd-1234-abcd-1234-abcd-1234
