on:
  pull_request:
    branches:
      - master
    types: [opened, reopened]
name: Pull Request Automation
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://${{ secrets.PARTNERSHIP_USER }}:${{ secrets.PARTNERSHIP_API_KEY }}@partnership-pipelines-api.jfrog.io/v1/projectIntegrations/356/hook"
          data: '{"branch":"${{ github.head_ref }}", "prurl": "${{ github.event.pull_request.html_url }}", "prtitle":"${{ github.event.pull_request.title }}", "prnumber":"${{ github.event.pull_request.number }}"}'
          method: 'POST'